### ISSUE TITLE
Some tests failing with the upcoming release of rnaturalearthdata

### ISSUE THREAD

**Issue by PMassicotte** [jbdorey/BeeBDC#10]
Hi.

We are planing to release rnaturlearthdata v1.0.0 which ends support to sp in favour of sf.

It appears that these two tests are failing:

https://github.com/jbdorey/BeeBDC/blob/2014ec3db2c1c6ea15f0fd20ad8561a8d5152cec/tests/testthat/test-countryOutlieRs.R#L32-L40

Can you confirm on your side?

Regards,
Phil

**Comment by jbdorey** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Hi Phil,Thanks for letting us know! I’ve had a little look and I think that the problem on the BeeBDC side is that the “iso_a3” column now returns -99 for (at least for this test) Norway and France. As do a few other columns. So, my question would be — should I be looking to use another column, or is this a data issue on your end? I know that country names and codes are a real pain, so hopefully this isn’t too difficult :)Warm regards,James P.S., Sorry, I’m just starting a new job next week and have been rushing around organising housing and the like.  
        
     
     
        
            Dr James Dorey - Lecturer in Biological Sciences at The University of WollongongJamesDoreyPhotography.com.au    Mobile: +61 401 421 073
                 

        
     
 On 5 February 2024 at 7:47:50 am, Philippe Massicotte ***@***.***) wrote: 
Hi.
We are planing to release rnaturlearthdata v1.0.0 which ends support to sp in favour of sf.
It appears that these two tests are failing:
https://github.com/jbdorey/BeeBDC/blob/2014ec3db2c1c6ea15f0fd20ad8561a8d5152cec/tests/testthat/test-countryOutlieRs.R#L32-L40
Can you confirm on your side?
Regards,
Phil

**Comment by jbdorey** [comment]
body{font-family:Helvetica,Arial;font-size:13px}And sorry, that is from using this code:countryMap <- rnaturalearth::ne_countries(returnclass = "sf", country = NULL,                                        type = "countries", scale = 50)  %>%      # buffer by zero and make geometry valid to avoid potential issues with polygon intersection    sf::st_make_valid() %>%  # Select only a subset of the naturalearthdata columns to extract  dplyr::select(iso_a2, iso_a3, name, name_long, continent, geometry) %>%  # Replace some country codes to match the checklist  dplyr::mutate(iso_a3 = iso_a3 %>% stringr::str_replace_all(    c("ALA" = "FIN", # Aland Islands == Finland    "ASM" = "WSM", # American Samoa == Samoa    "HKG" = "CHN", # Hong Kong == China    "MAF" = "SXM"))) # Saint-Martin == Sint Maarten  
        
     
     
        
            Dr James Dorey - Lecturer in Biological Sciences at The University of WollongongJamesDoreyPhotography.com.au    Mobile: +61 401 421 073
                 

        
     
 On 7 February 2024 at 2:13:32 pm, James Dorey ***@***.***) wrote: Hi Phil,Thanks for letting us know! I’ve had a little look and I think that the problem on the BeeBDC side is that the “iso_a3” column now returns -99 for (at least for this test) Norway and France. As do a few other columns. So, my question would be — should I be looking to use another column, or is this a data issue on your end? I know that country names and codes are a real pain, so hopefully this isn’t too difficult :)Warm regards,James P.S., Sorry, I’m just starting a new job next week and have been rushing around organising housing and the like.  
         
      
      
        
            Dr James Dorey - Lecturer in Biological Sciences at The University of WollongongJamesDoreyPhotography.com.au    Mobile: +61 401 421 073
                  

        
      
 On 5 February 2024 at 7:47:50 am, Philippe Massicotte ***@***.***) wrote: 
Hi.
We are planing to release rnaturlearthdata v1.0.0 which ends support to sp in favour of sf.
It appears that these two tests are failing:
https://github.com/jbdorey/BeeBDC/blob/2014ec3db2c1c6ea15f0fd20ad8561a8d5152cec/tests/testthat/test-countryOutlieRs.R#L32-L40
Can you confirm on your side?
Regards,
Phil

**Comment by PMassicotte** [comment]
Looks like that in the new version of the data, `iso_a3_eh` contains the info:

```r
library(rnaturalearthdata)
countries110[countries110$iso_a3_eh == "FRA"]
countries110[countries110$iso_a3_eh == "NOR"]
```

**Comment by PMassicotte** [comment]
Might have some info here: https://github.com/nvkelso/natural-earth-vector/issues/252

**Comment by jbdorey** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Hey Phil,Thanks for that detective work, indeed that has fixed up a few of these new -99 cells! Many thanks for your detective work! When are you planning your release? I will be starting work next week and high on my to-do-list is to run BeeBDC on an ARM mac and potentially a windows emulator using   work computers (although I think it still pass all tests without). Then I will try to push 1.0.4 as close to your release as I can! Many thanks,James   
        
     
     
        
            Dr James Dorey - Lecturer in Biological Sciences at The University of WollongongJamesDoreyPhotography.com.au    Mobile: +61 401 421 073
                 

        
     
 On 7 February 2024 at 11:35:54 pm, Philippe Massicotte ***@***.***) wrote: 
Might have some info here: nvkelso/natural-earth-vector#252

**Comment by PMassicotte** [comment]
Thank you very much!

I will submit later today :)
